export const FETCH_ALL = "FETCH_ALL";
export const CURRENT_PLAYLIST = "CURRENT_PLAYLIST";
export const NOW_PLAYING = "NOW_PLAYING";
export const SHOW_MODAL_WINDOW = "SHOW_MODAL_WINDOW";
export const UPDATE_ALBUM = "UPDATE_ALBUM";
